config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions'
             }
  devise_scope :user do
    get '/users/sign_out' => 'devise/session#destroy'

    authenticated :user do
      get 'dashboard', to: 'dashboard#index', as: :dashboard
      get '', to: 'dashboard#index'
    end

    resources :countries do
      resources :cities do
        resources :places
      end
    end

    unauthenticated :user do
      get 'dashboard', to: redirect('/users/sign_in')
    end
  end

  # root to: "countries#index"
  root to: 'landing_page#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  match '*unmatched', to: 'application#not_found_method', via: :all

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # before_action :authenticate_user!
  def index
    @q = current_user.countries.ransack(params[:q])
    order_by_name = params[:order] == 'desc' ? 'name DESC' : 'name ASC'
    order_by_created_at = params[:order] == 'desc' ? 'created_at DESC' : 'created_at ASC'

    @pagy, @countries = if params[:order_by] == 'name'
                          pagy(@q.result(distinct: true).order(order_by_name))
                        else
                          pagy(@q.result(distinct: true).order(order_by_created_at))
                        end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container-fluid">
  <% if @countries.empty? %>
    <div class="text-center mt-4">
      <h3>No countries found. Add one.</h3>
      <div class="mb-3">
        <%= link_to new_country_path, class: "btn btn-primary" do %>
          New country
          <%= fa_icon 'plus' %>
        <% end %>
      </div>
    
    </div>
  <% else %>
    <div class="d-flex justify-content-between align-items-center">
      <h1 class="display-4 mt-2">Dashboard</h1>
      <%= search_form_for @q, url: dashboard_path, method: :get do |f| %>
        <div class="input-group">
          <%= f.search_field :name_cont, class: 'form-control', placeholder: 'Search by country...' %>
          <div class="input-group-append">
            <%= f.submit 'Search', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <%= link_to new_country_path, class: "btn btn-primary" do %>
        New country
        <%= fa_icon 'plus' %>
      <% end %>
      <div class="d-flex align-items-center">
        <strong>Sort by:</strong>
        <div class="d-flex flex-column align-items-center mx-2">
          <%= link_to dashboard_path(order: 'asc', order_by: 'name'), class: "btn btn-link m-0 p-0" do %>
            <%= fa_icon 'sort-up' %> A-Z
          <% end %>
          <%= link_to dashboard_path(order: 'desc', order_by: 'name'), class: "btn btn-link m-0 p-0" do %>
            <%= fa_icon 'sort-down' %> Z-A
          <% end %>
        </div>
        <div class="d-flex flex-column">
          <%= link_to dashboard_path(order: 'desc', order_by: 'created_at'), class: "btn btn-link m-0 p-0" do %>
            <%= fa_icon 'sort-up' %> Newest
          <% end %>
          <%= link_to dashboard_path(order: 'asc', order_by: 'created_at'), class: "btn btn-link m-0 p-0" do %>
            <%= fa_icon 'sort-down' %> Oldest
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <table class="mt-2 table text-center table-bordered table-responsive">
          <thead>
            <tr>
              <th rowspan="2">Country Name</th>
              <th colspan="2">Cities</th>
              <th rowspan="2">Qty Places</th>
              <th rowspan="2">Actions</th>
            </tr>
            <tr>
              <th>Qty</th>     
              <th>Actions</th> 
            </tr>
          </thead>
          <tbody id="rows">
            <% @countries.each do |country| %>
              <tr>
                <td>
                  <%= highlight(country.name, params.dig(:q, :name_cont)) %>
                </td>
                <td>
                  <%= country.cities.count %>
                </td>
                <td>
                  <%= link_to country_cities_path(country), class: "btn btn-outline-primary" do %>
                    <%= fa_icon 'eye' %>
                  <% end %>
                  <%= link_to new_country_city_path(country), class: "btn btn-outline-primary" do %>
                    City <%= fa_icon 'plus' %>
                  <% end %>
                </td> 
                <td>
                  <%= country.cities.sum { |city| city.places.count } %>
                </td>
            
                <td class="d-flex justify-content-center">
                  <%= link_to(country_path(country), class: "btn btn-primary mx-1", title: "Edit this country") do %>  
                    <%= fa_icon 'eye' %> Country
                  <% end %>
                  <%= link_to(edit_country_path(country), class: "btn btn-warning mx-1", title: "Edit this country") do %>
                    <%= fa_icon 'edit' %> Edit
                  <% end %>
                  <%= button_to(country_path(country), method: :delete, data: {turbo_confirm: 'Are you sure you want to delete this country?' }, class: "btn btn-danger mx-1", title: "Delete this country") do %>
                    <%= fa_icon 'trash' %> Delete
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="d-flex justify-content-end">
          <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
          </div>
      </div>
    </div>
  <% end %>
</div>