config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions'
             }
  devise_scope :user do
    get '/users/sign_out' => 'devise/session#destroy'

    authenticated :user do
      get 'dashboard', to: 'dashboard#index', as: :dashboard
      get '', to: 'dashboard#index'
    end

    resources :countries do
      resources :cities do
        resources :places
      end
    end

    unauthenticated :user do
      get 'dashboard', to: redirect('/users/sign_in')
    end
  end

  # root to: "countries#index"
  root to: 'landing_page#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  match '*unmatched', to: 'application#not_found_method', via: :all

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/city.rb
class City < ApplicationRecord
  has_and_belongs_to_many :countries, join_table: 'countries_cities'
  has_many :places, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3 }, format: { without: /\d/ }
  validate :unique_name_within_country
  before_save :capitalize_name

  private

  def capitalize_name
    self.name = name[0].capitalize.concat(name[1..]) if name.present?
  end

  def unique_name_within_country
    return unless countries.any? { |country| country.cities.where.not(id:).exists?(name:) }

    errors.add(:name, 'A city with the same name already exists in this country.')
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :authenticate_user!
  before_action :set_city, only: %i[show edit update destroy]

  def index
    # First, check if a country_id is provided in the params
    country_id = params[:country_id] || session[:last_viewed_country_id]

    if country_id.present?
      @country = current_user.countries.find_by(id: country_id)

      if @country
        @pagy, @cities = pagy(@country.cities.order(:name))
      else
        flash[:alert] = 'Selected country does not exist or does not belong to you.'
        redirect_to countries_path
      end
    else
      @cities = []
    end
  end

  # GET /cities/1 or /cities/1.json
  def show
    # return unless @city.countries.any?

    # session[:last_viewed_country_id] = @city.countries.first.id
    # @city = City.find(params[:id])
    @country = @city.countries.first
  end

  # GET /cities/new
  def new
    @city = City.new
    @user_countries = current_user.countries
    @country = @user_countries.first
  end

  # GET /cities/1/edit
  def edit
    @user_countries = current_user.countries
  end

  # POST /cities or /cities.json
  def create
    @country = current_user.countries.find(params[:country_id])
    @city = @country.cities.build(city_params)

    selected_country_id = params[:city][:country_id]
    selected_country = current_user.countries.find_by(id: selected_country_id)

    if selected_country.nil?
      flash[:alert] = 'Please select a country first'
      redirect_to new_country_city_url(city_id: @city.id) and return
    end

    existing_city = selected_country.cities.find_by('LOWER(name) = ?', @city.name.downcase)

    if existing_city
      flash[:alert] = 'A city with the same name already exists in this country.'
      redirect_to new_country_city_path(selected_country, city_id: @city.id) and return
    end

    respond_to do |format|
      if @city.save
        @city.countries << selected_country
        format.html { redirect_to country_cities_path(selected_country), notice: 'City was successfully created.' }
        format.json { render :index, status: :created, location: @city }
      else
        @user_countries = current_user.countries
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    @city = City.find(params[:id])
    old_country = @city.countries.first

    selected_country_id = params[:city][:country_id]
    new_country = current_user.countries.find_by(id: selected_country_id)

    if new_country.nil?
      flash[:alert] = 'Please select a country first.'
      redirect_to edit_country_city_path and return
    end

    if new_country.cities.where.not(id: @city.id).where('lower(name) = ?', city_params[:name].downcase).exists?
      flash[:alert] = 'A city with the same name already exists in the selected country.'
      redirect_to edit_country_city_path and return
    end
    
    @user_countries = current_user.countries

    respond_to do |format|
      if @city.update(city_params)
        if old_country && old_country.id != new_country.id
          old_country.cities.delete(@city)
          new_country.cities << @city
        end
        format.html { redirect_to country_cities_url(new_country), notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy!

    respond_to do |format|
      format.html { redirect_to country_cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @country = current_user.countries.find(params[:country_id])
    @city = @country.cities.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def city_params
    params.require(:city).permit(:name, country_ids: [])
  end

  def catch_not_found(e)
    Rails.logger.debug('We had a not found exception.')
    flash.alert = e.to_s
    redirect_to countries_path
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>" class="card mt-3">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6 col-sm-4">
        <h5 class="card-title">Name:</h5>
      </div>
      <div class="col-md-6 col-sm-4">
        <p class="card-text"><%= city.name %></p>
      </div>
    </div>
  </div>
</div>

app/views/cities/_form.html.erb
<%= form_with(model: [@country, @city]) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>
      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <div class="col-md-6">
      <%= form.label :name, style: "display: block", class:"form-label" %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :country_id, 'Select a Country', class: "form-label" %>
    <%= form.collection_select :country_id, @user_countries, :id, :name, { prompt: 'Choose a country' } %>
  </div>
  
  <div class="mb-3">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<div class="container-fluid">
  <h1 class="display-4">Editing city</h1>
  <div class="row">
    <div class="col-md-6">
        <%= render "form", city: @city %>
    </div>
    <div>
      <%= link_to country_city_path(@country, @city), class: "btn btn-primary" do %>
        <%= fa_icon 'eye' %> City
      <% end %>
      <%= link_to country_cities_path(@country), class: "btn btn-secondary" do %>
        <%= fa_icon 'arrow-left' %> Cities
      <% end %>
    </div>
  </div>
</div>

app/views/cities/index.html.erb
<div class="container-fluid">
  <% if @country %>
    <h1 class="display-4 mt-3">Cities in <%= @country.name %></h1>

    <% if @cities.any? %>
      <div class="table-responsive mt-3">
        <table class="table table-bordered">
          <thead>
            <tr class="text-center">
              <th>Name</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @cities.each do |city| %>
              <tr class="text-center">
                <td><%= city.name %></td>
                <td>
                  <%= link_to country_city_path(@country, city), class: 'btn btn-primary' do %>
                    <%= fa_icon 'eye' %> City
                  <% end %>
                  <%= link_to country_city_places_path(@country, city), class: "btn btn-primary" do %>
                    <%= fa_icon 'eye' %> Places
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="d-flex align-items-center">
        <%= link_to new_country_city_path(@country), class: 'btn btn-primary' do %>
          <%= fa_icon 'plus' %> New city
        <% end %>
        <%= link_to dashboard_path, class: "btn btn-secondary mx-2" do %>
          <%= fa_icon 'arrow-left' %> Dashboard
        <% end %>

        <div class="ms-auto">
            <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>  
        </div>
      </div>
    <% else %>
      <div class="text-center">
        <p>No cities found.</p>
        <%= link_to new_country_city_path(country_id: @country.id), class: "btn btn-primary" do %>
          <%= fa_icon 'plus' %> Add City
        <% end %>
      </div>
      <%= link_to countries_path, class: "btn btn-secondary" do %>
        <%= fa_icon 'arrow-left' %> To countries
      <% end %>
    <% end %>
  <% else %>
    <p>No specific country selected. Showing all available cities.</p>
  <% end %>
</div>

app/views/cities/new.html.erb
<div class="container-fluid">
  <h1 class="display-4">New city</h1>
  <div class="row">
    <div class="col-md-6">
      <%= render "form", city: @city %>
      <% if @country.present? %>
        <%= link_to country_cities_path(@country, @city), class: "btn btn-secondary" do %>
          <%= fa_icon 'arrow-left' %> Cities
        <% end %>
      <% else %>
        <%= link_to cities_path, class: "btn btn-secondary" do %>
          <%= fa_icon 'arrow-left' %> Cities
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/cities/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 mt-2">
      <%= render @city %>
      <div class="d-flex mt-3">
          <%= link_to(country_cities_path(@country), class: "btn btn-secondary btn-icon mb-2", title: "Back to cities") do %>
          <%= fa_icon 'arrow-left' %> Cities
        <% end %>
        <%= link_to(edit_country_city_path(@country, @city), class: "btn btn-primary btn-icon mb-2 mx-2", title: "Edit this city") do %>
          <%= fa_icon 'edit' %> Edit
        <% end %>
        <%= button_to(country_city_path(@country, @city), method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this city?' }, class: "btn btn-danger btn-icon mb-2", title: "Delete this city") do %>
          <%= fa_icon 'trash' %> Delete
        <% end %>
      </div>
    </div>
  </div>
</div>