config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions'
             }
  devise_scope :user do
    get '/users/sign_out' => 'devise/session#destroy'

    authenticated :user do
      get 'dashboard', to: 'dashboard#index', as: :dashboard
      get '', to: 'dashboard#index'
    end

    resources :countries do
      resources :cities do
        resources :places
      end
    end

    unauthenticated :user do
      get 'dashboard', to: redirect('/users/sign_in')
    end
  end

  # root to: "countries#index"
  root to: 'landing_page#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  match '*unmatched', to: 'application#not_found_method', via: :all

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :city
  validates :name, presence: true, uniqueness: { scope: :city_id }
  validates :category, presence: true
  validates :rating, presence: true,
                     numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :comments, presence: true
  validates :city_id, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[category city_id comments created_at id id_value name rating updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    ['city']
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :authenticate_user!
  before_action :set_place, only: %i[show edit update destroy]
  before_action :set_user_cities, only: %i[index create new edit update]
  before_action :set_country_and_city, only: %i[index edit new show]

  # GET /places or /places.json
  def index
    @q = Place.where(city: @city).ransack(params[:q])
    @pagy, @places = pagy(@q.result(distinct: true).order(created_at: :desc))
  end

  # GET /places/1 or /places/1.json
  def show
    @place = Place.find(params[:id]) # Find the place
    @city = @place.city # Get the city associated with the place
    @country = @city.countries.first # Get the first country associated with the city
    @places = Place.where(city: @city) # Get all places within the same city
  end

  # GET /places/new
  def new
    @place = Place.new
    if params[:city_id].present?
      @city = City.find(params[:city_id])
      @country = @city.countries.first # Assuming you want the first country associated with the city
    else
      @country = Country.first
      @city = @country.cities.first
    end
    @place.city = @city
  end

  # GET /places/1/edit
  def edit; end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)
    user_city_ids = @user_cities.map(&:id)

    if user_city_ids.include?(@place.city_id)
      # Set @city based on the city_id of the new place
      @city = City.find(@place.city_id)
      # Set @country based on the first country associated with the city
      @country = @city.countries.first

      respond_to do |format|
        if @place.save
          format.html do
            redirect_to country_city_places_url(@country, @city), notice: 'Place was successfully created.'
          end
          format.json { render :show, status: :created, location: @place }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to new_place_path, alert: 'City is not valid or not accessible.' }
        format.json { render json: { error: 'City is not valid or not accessible' }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        @city = @place.city
        @country = @city.countries.first

        format.html { redirect_to country_city_places_url(@country, @city), notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy!

    respond_to do |format|
      format.html { redirect_to country_city_places_url(@country, @city), notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
    @city = @place.city
    @country = @city.countries.first
  end

  # Only allow a list of trusted parameters through.
  def place_params
    params.require(:place).permit(:name, :category, :rating, :comments, :city_id)
  end

  def set_user_cities
    user_countries = current_user.countries
    @user_cities = user_countries.map(&:cities).flatten.uniq
  end

  def set_country_and_city
    @country = Country.find(params[:country_id])
    @city = @country.cities.find(params[:city_id])
  end

  def catch_not_found(e)
    Rails.logger.debug('We had a not found exception.')
    flash.alert = e.to_s
    redirect_to places_path
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: [@country, @city, @place]) do |form| %>
  <% if place.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :category, class:"form-label" %>
    <%= form.text_field :category, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :rating, class:"form-label" %>
    <%= form.number_field :rating, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :comments, class:"form-label" %>
    <%= form.text_area :comments, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :city_id, 'Select a City' %>
    <%= form.collection_select :city_id, @user_cities, :id, :name, prompt: 'Select a city', class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div id="<%= dom_id place %>" class="card mb-3">
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <h5 class="card-title">Name:</h5>
      </div>
      <div class="col-md-9">
        <p class="card-text"><%= place.name %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <h5 class="card-title">Category:</h5>
      </div>
      <div class="col-md-9">
        <p class="card-text"><%= place.category %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <h5 class="card-title">Rating:</h5>
      </div>
      <div class="col-md-9">
        <p class="card-text"><%= place.rating %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <h5 class="card-title">Comments:</h5>
      </div>
      <div class="col-md-9">
        <p class="card-text"><%= place.comments %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <h5 class="card-title">City:</h5>
      </div>
      <div class="col-md-9">
        <p class="card-text"><%= place.city.name if place.city %></p>
      </div>
    </div>
  </div>
</div>

app/views/places/edit.html.erb
<div class="container-fluid">
  <h1 class="display-4">Edit place</h1>
  <div class="row">
    <div class="col-md-6">
      <%= render "form", place: @place %>
    </div>
    <div>
      <%= link_to country_city_places_path(@place), class: "btn btn-primary" do %>
        <%= fa_icon 'eye' %> Place
      <% end %>
      <%= link_to country_city_places_path(@country, @city), class: "btn btn-primary" do %>
        <%= fa_icon 'arrow-left' %> Places
      <% end %>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="container-fluid">
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="display-4 mt-2">Places in <%= @city.name %>:</h1>
    <%= search_form_for @q, url: country_city_places_path(@country, @city), method: :get do |f| %>
      <div class="input-group">
        <%= f.search_field :name_or_category_cont, class: 'form-control', placeholder: 'Name or category...' %>
        <div class="input-group-append">
          <%= f.submit 'Search', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <% if @places.any? %>
      <% @places.each do |place| %>
        <div class="col-md-4">
          <div class="card mb-3">
            <div class="card-body">
              <h5 class="card-title d-flex">
                <%= highlight(place.name, params.dig(:q, :name_cont)) %> 
                <span class="badge badge-secondary ms-auto" style="color: green;"><%= place.category %></span>
              </h5>
              <h6 class="card-subtitle mb-1 text-muted">City of <%= place.city.name %></h6>
              <p class="card-text">Rating: <%= place.rating %></p>
              <p class="card-text">Comments: <%= place.comments %></p>
              <%= link_to "View place", country_city_place_path(@country, @city, place), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="col-md-12 text-center">
        <p>No places found.</p>
        <%= link_to new_country_city_place_path(city_id: @city.id, country_id: @country.id), class: "btn btn-primary" do %>
          <%= fa_icon 'plus' %> New place
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="d-flex align-items-center mt-4">
    <% if @places.any? %>
      <%= link_to new_country_city_place_path, class: "btn btn-primary" do %>
        <%= fa_icon 'plus' %> Add Place
      <% end %>
    <% end %>
    <%= link_to dashboard_path, class: "btn btn-secondary mx-2" do %>
      <%= fa_icon 'arrow-left' %> Dashboard
    <% end %>
    <%= link_to(country_cities_path, class: "btn btn-outline-primary btn-icon", title: "Back to cities") do %>
      <%= fa_icon 'arrow-left' %> Cities
    <% end %>
    <div class="ms-auto mt-3">
        <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>

app/views/places/new.html.erb
<div class="container-fluid">
  <h1 class="display-4">New place</h1>
  <div class="row">
    <div class="col-md-6">
      <%= render "form", place: @place %>


      <%= link_to country_city_places_path(@country, @city), class: "btn btn-secondary btn-icon mb-2", title: "Back to places under this city" do %>
        <%= fa_icon 'arrow-left' %> Places
      <% end %>

  </div>
</div>
</div>

app/views/places/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 mt-3">
      <%= render @place %>
      <div class="mt-3">
        <%= link_to(edit_country_city_place_path(@country, @city, @place), class: "btn btn-primary btn-icon mb-2", title: "Edit this place") do %>
          <%= fa_icon 'edit' %> Edit
        <% end %>
       <%= link_to country_city_places_path(@country, @city), class: "btn btn-secondary btn-icon mb-2", title: "Back to places under this city" do %>
  <%= fa_icon 'arrow-left' %> Places
<% end %>

        <%= button_to(country_city_place_path(@country, @city, @place), method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this place?' }, class: "btn btn-danger btn-icon", title: "Destroy this place") do %>
          <%= fa_icon 'trash' %> Delete
        <% end %>
      </div>
    </div>
  </div>
</div>